-- Seed data generated from js/data.js — run once in Supabase SQL Editor

insert into stores (id, slug, name, tagline, description, logo_text, address, hours, whatsapp, categories, theme, theme_dark, translations) values
  ('lamset-jamal', 'lamset-jamal', 'لمسة جمال', 'جمالك يبدأ من لمسة', 'متجر لمسة جمال متخصص بمنتجات المكياج والعناية بالبشرة الأصلية، مختارة بعناية لتمنحك إطلالة واثقة يومياً.', 'لمسة جمال', 'الشارع الرئيسي - دخلة الصحة القديمة', 'يومياً: 9:00ص - 11:00م', '970599111222', '{"الكل","مكياج","عناية بالبشرة","عطور","أدوات تجميل"}', '{"primary":"#16342b","primaryDark":"#0d2119","secondary":"#DDEEE2","surface":"#F6FAF7","ink":"#12201A","accent":"#735c00"}'::jsonb, '{"primary":"#5aa885","primaryDark":"#3c7a5c","secondary":"#DDEEE2","surface":"#1c1e17","ink":"#e8e4d7","accent":"#d3c087"}'::jsonb, '{"en":{"name":"Lamset Jamal","logoText":"Lamset Jamal","tagline":"Your beauty begins with a touch","description":"Lamset Jamal is a specialized store for authentic makeup and skincare products, carefully selected to give you a confident look every day.","address":"Nablus - Rafidia Street - Al-Amal Building, 1st Floor","hours":"Daily: 9:00 AM - 11:00 PM"},"he":{"name":"למסת ג''מאל","logoText":"למסת ג''מאל","tagline":"היופי שלך מתחיל במגע","description":"למסת ג''מאל היא חנות המתמחה במוצרי איפור וטיפוח עור מקוריים, שנבחרו בקפידה כדי להעניק לך מראה בטוח בכל יום.","address":"שכם - רחוב רפידיה - בניין אל-אמל, קומה 1","hours":"כל יום: 09:00-23:00"}}'::jsonb),
  ('lamset-sabaya', 'lamset-sabaya', 'لمسة صبايا', 'ستايلك، حكاية بتحكيها', 'متجر لمسة صبايا لعشاق الموضة والإكسسوارات العصرية، تشكيلة متجددة تناسب كل الأذواق والمناسبات.', 'لمسة صبايا', 'الشارع الرئيسي - دخلة الصحة القديمة', 'يومياً: 9:00ص - 11:00م', '970599333444', '{"الكل","إكسسوارات","حقائب","مجوهرات","ملابس"}', '{"primary":"#8E5FA6","primaryDark":"#5F3B75","secondary":"#F1E6F7","surface":"#FBF7FD","ink":"#241A2B","accent":"#E6A23C"}'::jsonb, '{"primary":"#b891ce","primaryDark":"#8a5fa8","secondary":"#F1E6F7","surface":"#1c1e17","ink":"#e8e4d7","accent":"#f0b35c"}'::jsonb, '{"en":{"name":"Lamset Sabaya","logoText":"Lamset Sabaya","tagline":"Your style, a story you tell","description":"Lamset Sabaya is a store for fashion and modern accessory lovers, with a constantly refreshed collection suited to every taste and occasion.","address":"Nablus - Main Roundabout - Al-Nakheel Commercial Complex","hours":"Daily: 9:00 AM - 11:00 PM"},"he":{"name":"למסת סבאיא","logoText":"למסת סבאיא","tagline":"הסטייל שלך, סיפור שאת מספרת","description":"למסת סבאיא היא חנות לאוהבות אופנה ואביזרים עדכניים, עם קולקציה מתחדשת המתאימה לכל טעם ואירוע.","address":"שכם - הכיכר הראשית - מתחם אל-נח''יל המסחרי","hours":"כל יום: 09:00-23:00"}}'::jsonb),
  ('maaraz-lamset-jamal', 'maaraz-lamset-jamal', 'معرض لمسة جمال', 'هدايا وتفاصيل تلمس القلب', 'معرض لمسة جمال وجهتك للهدايا الفاخرة والعطور والديكور المنزلي الراقي لكل المناسبات.', 'معرض لمسة جمال', 'الشارع الرئيسي - دخلة الصحة القديمة', 'يومياً: 9:00ص - 11:00م', '970599555666', '{"الكل","عطور","هدايا","ديكور","شموع"}', '{"primary":"#1C1C1E","primaryDark":"#000000","secondary":"#EFE6D8","surface":"#FAF7F0","ink":"#1C1C1E","accent":"#C9A66B"}'::jsonb, '{"primary":"#cfa96e","primaryDark":"#a3814f","secondary":"#EFE6D8","surface":"#1c1e17","ink":"#e8e4d7","accent":"#e0c48f"}'::jsonb, '{"en":{"name":"Maaraz Lamset Jamal","logoText":"Maaraz Lamset Jamal","tagline":"Gifts and details that touch the heart","description":"Maaraz Lamset Jamal is your destination for luxury gifts, perfumes and elegant home decor for every occasion.","address":"Nablus - Old University Street - Next to Bank of Palestine","hours":"Daily: 9:00 AM - 11:00 PM"},"he":{"name":"מעראז'' למסת ג''מאל","logoText":"מעראז'' למסת ג''מאל","tagline":"מתנות ופרטים שנוגעים בלב","description":"מעראז'' למסת ג''מאל היא היעד שלך למתנות יוקרה, בשמים ועיצוב בית אלגנטי לכל אירוע.","address":"שכם - רחוב האוניברסיטה הישנה - ליד בנק פלסטין","hours":"כל יום: 09:00-23:00"}}'::jsonb)
on conflict (id) do nothing;

insert into products (id, store_id, name, category, price, old_price, image, images, description, colors, sizes, translations) values
  ('lj-001', 'lamset-jamal', 'روج مطفي - Velvet Red', 'مكياج', 45, 55, 'https://picsum.photos/seed/lj001/600/700', '{"https://picsum.photos/seed/lj001/600/700","https://picsum.photos/seed/lj001b/600/700"}', 'روج مطفي بتركيبة كريمية غنية بتدوم طول اليوم بدون ما يجفف الشفايف.', '{"#A6455C","#7C2E40","#C9A66B"}', '{}', '{"en":{"name":"Velvet Red Matte Lipstick","description":"A rich, creamy matte lipstick that lasts all day without drying your lips."},"he":{"name":"שפתון מאט אדום קטיפה","description":"שפתון מאט בטקסטורה קרמית עשירה שמחזיק כל היום בלי לייבש את השפתיים."}}'::jsonb),
  ('lj-002', 'lamset-jamal', 'كريم أساس مرطب SPF30', 'مكياج', 65, NULL, 'https://picsum.photos/seed/lj002/600/700', '{"https://picsum.photos/seed/lj002/600/700"}', 'فاونديشن خفيف يوحد لون البشرة وبيحميها من أشعة الشمس.', '{"#E9C9A3","#D9AE7E","#B98652"}', '{}', '{"en":{"name":"Moisturizing Foundation SPF30","description":"A lightweight foundation that evens skin tone and protects it from sun rays."},"he":{"name":"קרם בסיס לחות SPF30","description":"מייק-אפ קליל שמאחד את גוון העור ומגן עליו מקרני השמש."}}'::jsonb),
  ('lj-003', 'lamset-jamal', 'سيروم فيتامين C', 'عناية بالبشرة', 80, 95, 'https://picsum.photos/seed/lj003/600/700', '{"https://picsum.photos/seed/lj003/600/700"}', 'سيروم مضاد للأكسدة بيفتح البشرة ويقلل التصبغات مع الاستخدام اليومي.', '{}', '{}', '{"en":{"name":"Vitamin C Serum","description":"An antioxidant serum that brightens skin and reduces pigmentation with daily use."},"he":{"name":"סרום ויטמין C","description":"סרום אנטי-אוקסידנטי שמבהיר את העור ומפחית כתמי גוון בשימוש יומי."}}'::jsonb),
  ('lj-004', 'lamset-jamal', 'عطر Amber Bloom', 'عطور', 120, NULL, 'https://picsum.photos/seed/lj004/600/700', '{"https://picsum.photos/seed/lj004/600/700"}', 'عطر شرقي دافئ بمزيج من العنبر والفانيليا، ثبات طويل يدوم لساعات.', '{}', '{"30ml","50ml","100ml"}', '{"en":{"name":"Amber Bloom Perfume","description":"A warm oriental fragrance blending amber and vanilla, with long-lasting hours of wear."},"he":{"name":"בושם Amber Bloom","description":"בושם מזרחי חם המשלב ענבר ווניל, עם עמידות ארוכה לשעות."}}'::jsonb),
  ('lj-005', 'lamset-jamal', 'فرشاة مكياج احترافية (5 قطع)', 'أدوات تجميل', 55, 70, 'https://picsum.photos/seed/lj005/600/700', '{"https://picsum.photos/seed/lj005/600/700"}', 'طقم فرش مكياج ناعمة مناسبة للباودر والكونتور والآيشادو.', '{}', '{}', '{"en":{"name":"Professional Makeup Brush Set (5 pcs)","description":"A soft brush set suitable for powder, contour and eyeshadow."},"he":{"name":"סט מברשות איפור מקצועי (5 יחידות)","description":"סט מברשות רכות המתאימות לפודרה, קונטור וצללית."}}'::jsonb),
  ('lj-006', 'lamset-jamal', 'ماسكارا تكثيف وتطويل', 'مكياج', 38, NULL, 'https://picsum.photos/seed/lj006/600/700', '{"https://picsum.photos/seed/lj006/600/700"}', 'تركيبة مقاومة للماء بتعطي رموش كثيفة وطويلة من أول طبقة.', '{"أسود","بني داكن"}', '{}', '{"en":{"name":"Volumizing & Lengthening Mascara","description":"A waterproof formula giving thick, long lashes from the first coat."},"he":{"name":"מסקרה לנפח ואורך","description":"פורמולה עמידה במים שנותנת ריסים עבים וארוכים כבר מהשכבה הראשונה."}}'::jsonb),
  ('lj-007', 'lamset-jamal', 'كريم ليلي مغذي بالكولاجين', 'عناية بالبشرة', 90, 110, 'https://picsum.photos/seed/lj007/600/700', '{"https://picsum.photos/seed/lj007/600/700"}', 'كريم ليلي كثيف بيجدد خلايا البشرة أثناء النوم ويقلل من علامات التعب.', '{}', '{}', '{"en":{"name":"Collagen Nourishing Night Cream","description":"A rich night cream that renews skin cells while you sleep and reduces signs of tiredness."},"he":{"name":"קרם לילה מזין בקולגן","description":"קרם לילה עשיר שמחדש את תאי העור בזמן השינה ומפחית סימני עייפות."}}'::jsonb),
  ('lj-008', 'lamset-jamal', 'بلاشر بودرة طبيعي', 'مكياج', 32, NULL, 'https://picsum.photos/seed/lj008/600/700', '{"https://picsum.photos/seed/lj008/600/700"}', 'بلاشر بلمسة نهائية طبيعية يعطي إشراقة صحية للوجنتين.', '{"وردي مرجاني","خوخي","توتي"}', '{}', '{"en":{"name":"Natural Powder Blush","description":"A blush with a natural finish that gives cheeks a healthy glow."},"he":{"name":"סומק פודרה טבעי","description":"סומק בגימור טבעי שמעניק ללחיים זוהר בריא."}}'::jsonb),
  ('lj-009', 'lamset-jamal', 'عطر Rose Noir', 'عطور', 135, NULL, 'https://picsum.photos/seed/lj009/600/700', '{"https://picsum.photos/seed/lj009/600/700"}', 'عطر نسائي فخم بقلب من الورد الأسود والمسك الأبيض.', '{}', '{"30ml","50ml"}', '{"en":{"name":"Rose Noir Perfume","description":"A luxurious women''s fragrance with a heart of black rose and white musk."},"he":{"name":"בושם Rose Noir","description":"בושם נשי מפואר עם לב של ורד שחור ומושק לבן."}}'::jsonb),
  ('lj-010', 'lamset-jamal', 'مقشر وجه لطيف بالسكر البني', 'عناية بالبشرة', 42, 50, 'https://picsum.photos/seed/lj010/600/700', '{"https://picsum.photos/seed/lj010/600/700"}', 'مقشر طبيعي يزيل خلايا الجلد الميت ويترك البشرة ناعمة ومشرقة.', '{}', '{}', '{"en":{"name":"Gentle Brown Sugar Face Scrub","description":"A natural exfoliant that removes dead skin cells and leaves skin soft and radiant."},"he":{"name":"פילינג פנים עדין בסוכר חום","description":"פילינג טבעי המסיר תאי עור מתים ומשאיר את העור רך וקורן."}}'::jsonb),
  ('lj-011', 'lamset-jamal', 'مرآة مكياج مضيئة LED', 'أدوات تجميل', 150, 180, 'https://picsum.photos/seed/lj011/600/700', '{"https://picsum.photos/seed/lj011/600/700"}', 'مرآة بإضاءة LED قابلة للتعديل، تعمل بالشحن، مثالية لروتين المكياج اليومي.', '{}', '{}', '{"en":{"name":"LED Light-Up Makeup Mirror","description":"A rechargeable mirror with adjustable LED lighting, perfect for your daily makeup routine."},"he":{"name":"מראת איפור עם תאורת LED","description":"מראה נטענת עם תאורת LED מתכווננת, מושלמת לשגרת האיפור היומית."}}'::jsonb),
  ('lj-012', 'lamset-jamal', 'كونتور ستيك متعدد الاستخدام', 'مكياج', 48, NULL, 'https://picsum.photos/seed/lj012/600/700', '{"https://picsum.photos/seed/lj012/600/700"}', 'ستيك كونتور وهايلايتر بقوام سهل البليند لنحت وإضاءة الوجه بدقيقتين.', '{"فاتح","متوسط","غامق"}', '{}', '{"en":{"name":"Multi-Use Contour Stick","description":"A contour & highlight stick with an easy-to-blend texture to sculpt and light up your face in minutes."},"he":{"name":"מקל קונטור רב-שימושי","description":"מקל קונטור והיילייט בטקסטורה קלה למריחה לפיסול והארת הפנים תוך דקות."}}'::jsonb),
  ('ls-001', 'lamset-sabaya', 'طقم إكسسوارات لؤلؤ', 'إكسسوارات', 60, 75, 'https://picsum.photos/seed/ls001/600/700', '{"https://picsum.photos/seed/ls001/600/700"}', 'طقم يتكون من قلادة وأقراط بتصميم لؤلؤي أنيق يناسب السهرات.', '{"ذهبي","فضي"}', '{}', '{"en":{"name":"Pearl Accessory Set","description":"A set of an elegant pearl-design necklace and earrings, perfect for evenings."},"he":{"name":"סט אביזרי פנינים","description":"סט הכולל שרשרת ועגילים בעיצוב פנינים אלגנטי, מושלם לערבים."}}'::jsonb),
  ('ls-002', 'lamset-sabaya', 'حقيبة كتف جلد صناعي', 'حقائب', 95, NULL, 'https://picsum.photos/seed/ls002/600/700', '{"https://picsum.photos/seed/ls002/600/700"}', 'حقيبة عملية بتصميم عصري مناسبة للاستخدام اليومي والجامعة.', '{"أسود","بيج","بورجوندي"}', '{}', '{"en":{"name":"Faux Leather Shoulder Bag","description":"A practical bag with a modern design, suitable for daily use and university."},"he":{"name":"תיק כתף מעור סינטטי","description":"תיק פרקטי בעיצוב מודרני, מתאים לשימוש יומיומי וללימודים."}}'::jsonb),
  ('ls-003', 'lamset-sabaya', 'سوار سلسلة ذهبي مطلي', 'مجوهرات', 40, 50, 'https://picsum.photos/seed/ls003/600/700', '{"https://picsum.photos/seed/ls003/600/700"}', 'سوار خفيف مطلي بالذهب مقاوم للاسمرار مع الاستخدام العادي.', '{}', '{}', '{"en":{"name":"Gold-Plated Chain Bracelet","description":"A lightweight gold-plated bracelet resistant to tarnishing with regular use."},"he":{"name":"צמיד שרשרת מצופה זהב","description":"צמיד קליל מצופה זהב, עמיד בפני התכהות בשימוש רגיל."}}'::jsonb),
  ('ls-004', 'lamset-sabaya', 'بلوزة صيفية واسعة', 'ملابس', 70, NULL, 'https://picsum.photos/seed/ls004/600/700', '{"https://picsum.photos/seed/ls004/600/700"}', 'قماش خفيف مريح مناسب للأجواء الحارة بقصة عصرية.', '{"أبيض","سماوي","وردي"}', '{"S","M","L","XL"}', '{"en":{"name":"Loose Summer Blouse","description":"Light, comfortable fabric suited for hot weather with a modern cut."},"he":{"name":"חולצת קיץ רחבה","description":"בד קליל ונוח המתאים למזג אוויר חם, בגזרה מודרנית."}}'::jsonb),
  ('ls-005', 'lamset-sabaya', 'نظارة شمسية كات آي', 'إكسسوارات', 55, 65, 'https://picsum.photos/seed/ls005/600/700', '{"https://picsum.photos/seed/ls005/600/700"}', 'نظارة بتصميم كات آي عصري مع حماية من الأشعة فوق البنفسجية.', '{"أسود","بني","شفاف"}', '{}', '{"en":{"name":"Cat Eye Sunglasses","description":"Modern cat-eye design sunglasses with UV protection."},"he":{"name":"משקפי שמש קאט איי","description":"משקפי שמש בעיצוב קאט איי מודרני עם הגנה מקרינת UV."}}'::jsonb),
  ('ls-006', 'lamset-sabaya', 'خاتم فضة تصميم مميز', 'مجوهرات', 35, NULL, 'https://picsum.photos/seed/ls006/600/700', '{"https://picsum.photos/seed/ls006/600/700"}', 'خاتم فضة عيار925 بتصميم بسيط وأنيق يناسب كل الإطلالات.', '{}', '{"16","17","18"}', '{"en":{"name":"Distinctive Design Silver Ring","description":"A 925 sterling silver ring with a simple, elegant design that suits every look."},"he":{"name":"טבעת כסף בעיצוב ייחודי","description":"טבעת כסף 925 בעיצוב פשוט ואלגנטי שמתאים לכל לוק."}}'::jsonb),
  ('ls-007', 'lamset-sabaya', 'حقيبة يد صغيرة للسهرة', 'حقائب', 85, 100, 'https://picsum.photos/seed/ls007/600/700', '{"https://picsum.photos/seed/ls007/600/700"}', 'كلاتش أنيق مزين بالكريستال مناسب للحفلات والمناسبات.', '{"ذهبي","فضي","أسود"}', '{}', '{"en":{"name":"Small Evening Handbag","description":"An elegant crystal-embellished clutch perfect for parties and occasions."},"he":{"name":"תיק יד קטן לערב","description":"קלאץ'' אלגנטי משובץ קריסטלים, מושלם למסיבות ואירועים."}}'::jsonb),
  ('ls-008', 'lamset-sabaya', 'فستان كاجوال منقوش', 'ملابس', 110, NULL, 'https://picsum.photos/seed/ls008/600/700', '{"https://picsum.photos/seed/ls008/600/700"}', 'فستان يومي مريح بطبعات ناعمة يناسب الخروجات الصباحية.', '{"كحلي","زيتي"}', '{"S","M","L"}', '{"en":{"name":"Casual Printed Dress","description":"A comfortable everyday dress with soft prints, perfect for morning outings."},"he":{"name":"שמלת קז''ואל מודפסת","description":"שמלה נוחה יומיומית עם הדפסים עדינים, מושלמת ליציאות בוקר."}}'::jsonb),
  ('ls-009', 'lamset-sabaya', 'طقم أقراط دائرية', 'مجوهرات', 28, 35, 'https://picsum.photos/seed/ls009/600/700', '{"https://picsum.photos/seed/ls009/600/700"}', 'أقراط خفيفة الوزن مناسبة للاستخدام اليومي بلمسة عصرية.', '{}', '{}', '{"en":{"name":"Round Earrings Set","description":"Lightweight earrings suitable for daily wear with a modern touch."},"he":{"name":"סט עגילים עגולים","description":"עגילים קלי משקל המתאימים לשימוש יומיומי עם נגיעה מודרנית."}}'::jsonb),
  ('ls-010', 'lamset-sabaya', 'وشاح حرير منقوش', 'إكسسوارات', 45, NULL, 'https://picsum.photos/seed/ls010/600/700', '{"https://picsum.photos/seed/ls010/600/700"}', 'وشاح ناعم الملمس بطبعات مميزة يكمل أي إطلالة بلمسة أنيقة.', '{"متعدد الألوان"}', '{}', '{"en":{"name":"Printed Silk Scarf","description":"A soft-touch scarf with distinctive prints that completes any look with an elegant touch."},"he":{"name":"צעיף משי מודפס","description":"צעיף רך למגע עם הדפסים ייחודיים שמשלים כל לוק בנגיעה אלגנטית."}}'::jsonb),
  ('ls-011', 'lamset-sabaya', 'حزام خصر جلد عريض', 'إكسسوارات', 38, 45, 'https://picsum.photos/seed/ls011/600/700', '{"https://picsum.photos/seed/ls011/600/700"}', 'حزام عريض يبرز الخصر ويناسب الفساتين والبناطيل الواسعة.', '{"أسود","بني"}', '{}', '{"en":{"name":"Wide Leather Waist Belt","description":"A wide belt that accentuates the waist, suitable for dresses and wide-leg pants."},"he":{"name":"חגורת מותניים רחבה מעור","description":"חגורה רחבה שמדגישה את המותניים, מתאימה לשמלות ומכנסיים רחבים."}}'::jsonb),
  ('ls-012', 'lamset-sabaya', 'حقيبة ظهر صغيرة عصرية', 'حقائب', 78, NULL, 'https://picsum.photos/seed/ls012/600/700', '{"https://picsum.photos/seed/ls012/600/700"}', 'حقيبة ظهر صغيرة عملية وأنيقة مناسبة للجامعة والخروجات.', '{"بيج","أسود"}', '{}', '{"en":{"name":"Modern Small Backpack","description":"A small, practical and stylish backpack suitable for university and outings."},"he":{"name":"תיק גב קטן ומודרני","description":"תיק גב קטן, פרקטי ואלגנטי, מתאים ללימודים וליציאות."}}'::jsonb),
  ('mz-001', 'maaraz-lamset-jamal', 'عطر Oud Royal فاخر', 'عطور', 210, 250, 'https://picsum.photos/seed/mz001/600/700', '{"https://picsum.photos/seed/mz001/600/700"}', 'عطر عود فاخر بتركيبة شرقية غنية مناسب للمناسبات الخاصة.', '{}', '{"50ml","100ml"}', '{"en":{"name":"Oud Royal Luxury Perfume","description":"A luxurious oud fragrance with a rich oriental blend, suitable for special occasions."},"he":{"name":"בושם Oud Royal יוקרתי","description":"בושם עוד יוקרתי בתערובת מזרחית עשירה, מתאים לאירועים מיוחדים."}}'::jsonb),
  ('mz-002', 'maaraz-lamset-jamal', 'طقم هدية عناية فاخر', 'هدايا', 130, NULL, 'https://picsum.photos/seed/mz002/600/700', '{"https://picsum.photos/seed/mz002/600/700"}', 'طقم هدية أنيق يحتوي على منتجات عناية مختارة معبأة بعلبة فاخرة.', '{}', '{}', '{"en":{"name":"Luxury Care Gift Set","description":"An elegant gift set with selected care products packed in a luxurious box."},"he":{"name":"סט מתנה יוקרתי לטיפוח","description":"סט מתנה אלגנטי הכולל מוצרי טיפוח נבחרים ארוזים בקופסה יוקרתית."}}'::jsonb),
  ('mz-003', 'maaraz-lamset-jamal', 'شمعة معطرة بالفانيليا', 'شموع', 45, 55, 'https://picsum.photos/seed/mz003/600/700', '{"https://picsum.photos/seed/mz003/600/700"}', 'شمعة طبيعية بوقت احتراق طويل تعطي أجواء دافئة ومريحة.', '{}', '{}', '{"en":{"name":"Vanilla Scented Candle","description":"A natural candle with a long burn time that creates a warm, cozy atmosphere."},"he":{"name":"נר ריחני בניחוח וניל","description":"נר טבעי עם זמן בעירה ארוך שיוצר אווירה חמימה ונעימה."}}'::jsonb),
  ('mz-004', 'maaraz-lamset-jamal', 'مزهرية سيراميك ديكور', 'ديكور', 90, NULL, 'https://picsum.photos/seed/mz004/600/700', '{"https://picsum.photos/seed/mz004/600/700"}', 'مزهرية سيراميك بتصميم عصري تضيف لمسة أناقة لأي ركن بالمنزل.', '{"أبيض","تراكوتا"}', '{}', '{"en":{"name":"Ceramic Decor Vase","description":"A modern-design ceramic vase that adds an elegant touch to any corner of the home."},"he":{"name":"אגרטל קרמיקה לעיצוב","description":"אגרטל קרמיקה בעיצוב מודרני שמוסיף נגיעה אלגנטית לכל פינה בבית."}}'::jsonb),
  ('mz-005', 'maaraz-lamset-jamal', 'بخور فاخر معطر', 'عطور', 55, 65, 'https://picsum.photos/seed/mz005/600/700', '{"https://picsum.photos/seed/mz005/600/700"}', 'بخور بخلطة فاخرة يعطي رائحة عود ومسك تدوم بالمكان لساعات.', '{}', '{}', '{"en":{"name":"Luxury Scented Incense","description":"Incense with a luxurious blend giving an oud and musk scent that lingers for hours."},"he":{"name":"קטורת מפוארת ריחנית","description":"קטורת בתערובת יוקרתית המעניקה ריח עוד ומושק שנשאר לשעות."}}'::jsonb),
  ('mz-006', 'maaraz-lamset-jamal', 'علبة هدايا شوكولاتة فاخرة', 'هدايا', 75, NULL, 'https://picsum.photos/seed/mz006/600/700', '{"https://picsum.photos/seed/mz006/600/700"}', 'تشكيلة شوكولاتة بلجيكية فاخرة معبأة بعلبة هدايا أنيقة.', '{}', '{}', '{"en":{"name":"Luxury Chocolate Gift Box","description":"A selection of luxurious Belgian chocolate packed in an elegant gift box."},"he":{"name":"קופסת מתנה שוקולד יוקרתי","description":"מבחר שוקולד בלגי יוקרתי ארוז בקופסת מתנה אלגנטית."}}'::jsonb),
  ('mz-007', 'maaraz-lamset-jamal', 'شمعتان في طقم زجاجي', 'شموع', 65, 80, 'https://picsum.photos/seed/mz007/600/700', '{"https://picsum.photos/seed/mz007/600/700"}', 'طقم شمعتين برائحتين مختلفتين بعبوة زجاجية أنيقة قابلة لإعادة الاستخدام.', '{}', '{}', '{"en":{"name":"Two-Candle Glass Set","description":"A set of two candles with different scents in an elegant, reusable glass jar."},"he":{"name":"סט שני נרות בכלי זכוכית","description":"סט של שני נרות בשני ריחות שונים באריזת זכוכית אלגנטית לשימוש חוזר."}}'::jsonb),
  ('mz-008', 'maaraz-lamset-jamal', 'لوحة ديكور جدارية', 'ديكور', 120, NULL, 'https://picsum.photos/seed/mz008/600/700', '{"https://picsum.photos/seed/mz008/600/700"}', 'لوحة جدارية بإطار خشبي فاخر تضيف طابع راقي لغرف الجلوس.', '{}', '{}', '{"en":{"name":"Wall Decor Painting","description":"A wall painting with a luxurious wooden frame that adds an elegant touch to living rooms."},"he":{"name":"תמונת קיר לעיצוב","description":"תמונת קיר עם מסגרת עץ יוקרתית שמוסיפה אופי אלגנטי לסלון."}}'::jsonb),
  ('mz-009', 'maaraz-lamset-jamal', 'عطر Musk White', 'عطور', 150, 175, 'https://picsum.photos/seed/mz009/600/700', '{"https://picsum.photos/seed/mz009/600/700"}', 'عطر مسك أبيض ناعم يمنحك إحساس بالنظافة والانتعاش طوال اليوم.', '{}', '{"30ml","50ml","100ml"}', '{"en":{"name":"Musk White Perfume","description":"A soft white musk fragrance that gives you a feeling of cleanliness and freshness all day."},"he":{"name":"בושם Musk White","description":"בושם מושק לבן ועדין שמעניק תחושת ניקיון ורעננות לאורך כל היום."}}'::jsonb),
  ('mz-010', 'maaraz-lamset-jamal', 'سلة هدايا مناسبات مميزة', 'هدايا', 160, NULL, 'https://picsum.photos/seed/mz010/600/700', '{"https://picsum.photos/seed/mz010/600/700"}', 'سلة هدايا متكاملة تجمع عطور وشموع وشوكولاتة لمناسبة خاصة.', '{}', '{}', '{"en":{"name":"Special Occasion Gift Basket","description":"A complete gift basket combining perfumes, candles and chocolate for a special occasion."},"he":{"name":"סל מתנה לאירועים מיוחדים","description":"סל מתנה מושלם המשלב בשמים, נרות ושוקולד לאירוע מיוחד."}}'::jsonb),
  ('mz-011', 'maaraz-lamset-jamal', 'إناء بخور نحاسي', 'ديكور', 70, 85, 'https://picsum.photos/seed/mz011/600/700', '{"https://picsum.photos/seed/mz011/600/700"}', 'إناء بخور نحاسي بنقشة تراثية يضيف لمسة أصالة للمجلس.', '{}', '{}', '{"en":{"name":"Copper Incense Burner","description":"A copper incense burner with a heritage pattern that adds an authentic touch to any sitting room."},"he":{"name":"מחתת קטורת מנחושת","description":"מחתת קטורת מנחושת עם תבנית מסורתית שמוסיפה נגיעה אותנטית לסלון."}}'::jsonb),
  ('mz-012', 'maaraz-lamset-jamal', 'شمعة عود ومسك كبيرة', 'شموع', 58, NULL, 'https://picsum.photos/seed/mz012/600/700', '{"https://picsum.photos/seed/mz012/600/700"}', 'شمعة كبيرة بخلطة عود ومسك، مثالية كهدية أو للاستخدام المنزلي.', '{}', '{}', '{"en":{"name":"Large Oud & Musk Candle","description":"A large candle with an oud and musk blend, perfect as a gift or for home use."},"he":{"name":"נר גדול עוד ומושק","description":"נר גדול בתערובת עוד ומושק, מושלם כמתנה או לשימוש ביתי."}}'::jsonb)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
